### ISSUE TITLE
7-Zip

### ISSUE THREAD

**Issue by D1mar0n** [6ilent/Electralyzed#1]
Hi! Please add the ability to specify the path to the program 7-Zip to be able to work with portable version of this program. Thank you in advance.

**Comment by 6ilent** [comment]
Planning on compiling it with 7zip so you don’t have to have it installed as it comes with it built in.

**Comment by D1mar0n** [comment]
Thanks for the answer! It will be very cool. I'll look forward to the new version with impatience. Thanks for your work!

Отправлено с iPhone
